project_id = "wskgiipqjtptptinnodb"

[functions.generate-sermon]
verify_jwt = false

[functions.translate-word]
verify_jwt = false

[functions.search-verses]
verify_jwt = false

[functions.save-public-sermon]
verify_jwt = true